app.config:
    charset:       UTF-8
    error_handler: null
    csrf_protection: { enabled: true, secret: xxxxxxxxxx }
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    form: test
    templating:
        escaping:       htmlspecialchars
        #assets_version: SomeVersionScheme
        engine: twig
    session:
        default_locale: en
        lifetime: 3600
        
## Twig Configuration
twig.config: 
    debug: "%kernel.debug%"

## Doctrine Configuration
doctrine.dbal:
    driver:   pdo_mysql
    dbname:   symfony_admin_sandbox
    user:     adminsandbox
    password: adminsandbox
    
doctrine.orm:
    mappings:
        SandboxBundle: ~

## Swiftmailer Configuration
#swiftmailer.config:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx

# Admin Configuration
base_application.config:
    entities:
        post:
            label:      Post
            group:      Blog
            class:      Application\SandboxBundle\Admin\PostAdmin
            entity:     Application\SandboxBundle\Entity\Post
            controller: Application\SandboxBundle\Controller\PostAdminController

        tag:
            label:      Tag
            group:      Blog
            class:      Application\SandboxBundle\Admin\TagAdmin
            entity:     Application\SandboxBundle\Entity\Tag
            controller: Application\SandboxBundle\Controller\TagAdminController

        comment:
            label:      Comment
            group:      Blog
            class:      Application\SandboxBundle\Admin\CommentAdmin
            entity:     Application\SandboxBundle\Entity\Comment
            controller: Application\SandboxBundle\Controller\CommentAdminController
